# Preprocessing with numpy


In [1]:
import numpy as np

1.checking for missing values
np.isnan(): Return an array with the same shape and size as the one we input.
every individual element of the original array  is replaced with a boolean(True/False) :True :missing value.
np.isnan(filename).sum():it will return the total no:of missing values.
missing values are filled with highest value in dataset....
hh=np.genfromtxt(filename,delimiter=)
t=np.nanmax(hh).round(2)+1
once again import....
hh=np.genfromtxt(filename,delimiter='',filling_values=t)


In [3]:
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric.csv"
lending_co_data_numeric=np.loadtxt(filename,delimiter=',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [5]:
np.isnan(lending_co_data_numeric)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]], shape=(1043, 6))

In [6]:
np.isnan(lending_co_data_numeric).sum()

np.int64(0)

In [12]:
#checking another file.
import numpy as np
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric-NAN.csv"
lending_co_data_nan=np.genfromtxt(filename,delimiter=';')
np.isnan(lending_co_data_nan).sum()


np.int64(260)

In [13]:
#we can fill values while loading.
import numpy as np
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric-NAN.csv"
lending_co_data_nan=np.genfromtxt(filename,delimiter=';',filling_values=0)
np.isnan(lending_co_data_nan).sum()

np.int64(0)

In [17]:
#1st approach:fill value with highest value in the dataset.
import numpy as np
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric-NAN.csv"
lending_co_data_nan=np.genfromtxt(filename,delimiter=';')
temp=np.nanmax(lending_co_data_nan).round(2)+1
temp

np.float64(64002.0)

In [19]:
#filling with new value.
import numpy as np
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric-NAN.csv"
lending_co_data_nan=np.genfromtxt(filename,delimiter=';',filling_values=temp)
np.isnan(lending_co_data_nan)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]], shape=(1043, 6))

In [20]:
np.isnan(lending_co_data_nan).sum()


np.int64(0)

2. substituting missing values in nd array:

np.where()

In [21]:
import numpy as np
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric-NAN.csv"
lending_co_data_numeric_nan=np.genfromtxt(filename,delimiter=';')
lending_co_data_numeric_nan


array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [25]:
temporary_mean=np.mean(lending_co_data_numeric,axis=0).round(2)
temporary_mean[0]

np.float64(2257.43)

In [27]:
temporary_fill=np.nanmax(lending_co_data_numeric_nan).round(2)+1
temporary_fill

np.float64(64002.0)

In [29]:
import numpy as np
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric-NAN.csv"
lending_co_data_numeric_nan=np.genfromtxt(filename,delimiter=';',filling_values=temporary_fill)
lending_co_data_numeric_nan

array([[2.0000e+03, 4.0000e+01, 3.6500e+02, 3.1210e+03, 4.2410e+03,
        1.3621e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 3.0610e+03, 4.1710e+03,
        1.5041e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.1600e+03, 3.2800e+03,
        1.5340e+04],
       ...,
       [6.4002e+04, 4.0000e+01, 3.6500e+02, 4.2010e+03, 5.0010e+03,
        1.6600e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.0800e+03, 3.3200e+03,
        1.5600e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 4.6010e+03, 4.6010e+03,
        1.6600e+04]], shape=(1043, 6))

In [33]:
for i in range(lending_co_data_numeric_nan.shape[1]):
    lending_co_data_numeric_nan[:,i]=np.where(lending_co_data_numeric_nan[:,i]==temporary_fill,temporary_mean[i],lending_co_data_numeric_nan[:,i])

In [34]:
lending_co_data_numeric_nan

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2257.43,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]],
      shape=(1043, 6))

In [ ]:
#if we need to replace -ve values......
for i in range(lending_co_data_numeric_nan.shape[1]):
    lending_co_data_numeric_nan[:,i]=np.where(lending_co_data_numeric_nan[:,i]<0,0,lending_co_data_numeric_nan[:,i])

3.Reshaping

In [35]:
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric.csv"
lending_co_data_numeric=np.loadtxt(filename,delimiter=',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [36]:
lending_co_data_numeric.shape

(1043, 6)

In [37]:
np.reshape(lending_co_data_numeric,(6,1043)) #1043*6=6*1043

array([[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
       [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
       [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
       [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]],
      shape=(6, 1043))

In [38]:
np.reshape(lending_co_data_numeric,(3,2086)) #1043*6=3*2086

array([[ 2000.,    40.,   365., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  4601.,  4601., 16600.]],
      shape=(3, 2086))

In [39]:
np.reshape(lending_co_data_numeric,(2,3,1043)) #1043*6=2*3*1043
#that is when we are reshaping the products of the dimensions should be equal.

array([[[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
        [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
        [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.]],

       [[ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
        [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
        [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]]],
      shape=(2, 3, 1043))

In [40]:
np.reshape(lending_co_data_numeric,(1,1,2,3,1043))

#some functions only input arrays of multiple dimensions in that case we can give 1 like
#this and can convert array into multiple dimensions.

array([[[[[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
          [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
          [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.]],

         [[ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
          [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
          [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]]]]],
      shape=(1, 1, 2, 3, 1043))

In [41]:
lending_co_data_numeric
# np.reshape() : it will not change the original array.

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [42]:
lending_co_data_numeric.reshape(6,1043)

array([[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
       [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
       [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
       [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]],
      shape=(6, 1043))

4.Removing values from array


In [43]:
import numpy as np

In [44]:
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric.csv"
lending_co_data_numeric=np.loadtxt(filename,delimiter=',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [45]:
np.delete(lending_co_data_numeric,0) #removed 1st element

array([   40.,   365.,  3121., ...,  4601.,  4601., 16600.], shape=(6257,))

In [46]:
np.delete(lending_co_data_numeric,0,axis=0) #removed 1st row

array([[ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1042, 6))

In [47]:
np.delete(lending_co_data_numeric,1,axis=0) #removed 2nd row

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1042, 6))

In [49]:
np.delete(lending_co_data_numeric,0,axis=1) #removed 1st column

array([[   40.,   365.,  3121.,  4241., 13621.],
       [   40.,   365.,  3061.,  4171., 15041.],
       [   40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  4201.,  5001., 16600.],
       [   40.,   365.,  2080.,  3320., 15600.],
       [   40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 5))

In [50]:
np.delete(lending_co_data_numeric,1,axis=1) #removed 2nd column

array([[ 2000.,   365.,  3121.,  4241., 13621.],
       [ 2000.,   365.,  3061.,  4171., 15041.],
       [ 1000.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,   365.,  4201.,  5001., 16600.],
       [ 1000.,   365.,  2080.,  3320., 15600.],
       [ 2000.,   365.,  4601.,  4601., 16600.]], shape=(1043, 5))

In [51]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [52]:
#to delete 1st rows....2,3,6 and to delete columns 1,3,5
np.delete(np.delete(lending_co_data_numeric,[1,2,5],axis=0),[0,2,4],axis=1)

array([[   40.,  3121., 13621.],
       [   40.,  3041., 15321.],
       [   50.,  3470., 13720.],
       ...,
       [   40.,  4201., 16600.],
       [   40.,  2080., 15600.],
       [   40.,  4601., 16600.]], shape=(1040, 3))

4.Sorting Ndarrays

In [80]:
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric.csv"
lending_co_data_numeric=np.loadtxt(filename,delimiter=',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [81]:
np.sort(lending_co_data_numeric)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [82]:
np.sort(lending_co_data_numeric,axis=0) #it will provide output as 1.00000e  something so next line

array([[ 1000.,    35.,   365., -2870., -2870.,  -350.],
       [ 1000.,    35.,   365., -2550., -2100.,   150.],
       [ 1000.,    35.,   365., -2450., -2000.,  1100.],
       ...,
       [ 9000.,   125.,   365., 16751., 18751., 54625.],
       [ 9000.,   165.,   365., 17650., 20001., 54625.],
       [ 9000.,   165.,   365., 19001., 22001., 64001.]], shape=(1043, 6))

In [85]:
np.set_printoptions(suppress=True) #to make result user friendly.that is from 
                                   #scientific calculations to normal

In [86]:
np.sort(lending_co_data_numeric,axis=0)

array([[ 1000.,    35.,   365., -2870., -2870.,  -350.],
       [ 1000.,    35.,   365., -2550., -2100.,   150.],
       [ 1000.,    35.,   365., -2450., -2000.,  1100.],
       ...,
       [ 9000.,   125.,   365., 16751., 18751., 54625.],
       [ 9000.,   165.,   365., 17650., 20001., 54625.],
       [ 9000.,   165.,   365., 19001., 22001., 64001.]], shape=(1043, 6))

In [87]:
np.sort(lending_co_data_numeric,axis=None)  #it will sort the 2d aray as flat

array([-2870., -2870., -2550., ..., 54625., 54625., 64001.], shape=(6258,))

In [88]:
np.sort(lending_co_data_numeric)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [89]:
#trick for descending order sorting.but every element will be negative.put -ve inside fn
np.sort(-lending_co_data_numeric)

array([[-13621.,  -4241.,  -3121.,  -2000.,   -365.,    -40.],
       [-15041.,  -4171.,  -3061.,  -2000.,   -365.,    -40.],
       [-15340.,  -3280.,  -2160.,  -1000.,   -365.,    -40.],
       ...,
       [-16600.,  -5001.,  -4201.,  -2000.,   -365.,    -40.],
       [-15600.,  -3320.,  -2080.,  -1000.,   -365.,    -40.],
       [-16600.,  -4601.,  -4601.,  -2000.,   -365.,    -40.]],
      shape=(1043, 6))

In [90]:
#by putting -ve like this....we can remove -ve signs
-np.sort(-lending_co_data_numeric)

array([[13621.,  4241.,  3121.,  2000.,   365.,    40.],
       [15041.,  4171.,  3061.,  2000.,   365.,    40.],
       [15340.,  3280.,  2160.,  1000.,   365.,    40.],
       ...,
       [16600.,  5001.,  4201.,  2000.,   365.,    40.],
       [15600.,  3320.,  2080.,  1000.,   365.,    40.],
       [16600.,  4601.,  4601.,  2000.,   365.,    40.]], shape=(1043, 6))

In [91]:
#that is in a single step ...descending can be done like:
-np.sort(-lending_co_data_numeric)

array([[13621.,  4241.,  3121.,  2000.,   365.,    40.],
       [15041.,  4171.,  3061.,  2000.,   365.,    40.],
       [15340.,  3280.,  2160.,  1000.,   365.,    40.],
       ...,
       [16600.,  5001.,  4201.,  2000.,   365.,    40.],
       [15600.,  3320.,  2080.,  1000.,   365.,    40.],
       [16600.,  4601.,  4601.,  2000.,   365.,    40.]], shape=(1043, 6))

In [92]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [93]:
#will sort 4th column in ascending order.
np.sort(lending_co_data_numeric[:,3])

array([-2870., -2550., -2450., ..., 16751., 17650., 19001.], shape=(1043,))

In [94]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [95]:
lending_co_data_numeric.sort(axis=1)
lending_co_data_numeric

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]], shape=(1043, 6))

by using .sort after variable..it is replacing the original array.that is the issue.

5.Argument Sorting in numpy
np.argsort()

In [97]:
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric.csv"
lending_co_data_numeric=np.loadtxt(filename,delimiter=',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [99]:
np.argsort(lending_co_data_numeric)  #it will return the indices for sorting....
"""in the output below..in the first row...1,2,0   means it have to be sorted...that is element corresponding to index 1 that is 40 is first then element corresponding to 
2 that is 365 is second and so on....."""

array([[1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       ...,
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5]], shape=(1043, 6))

In [103]:
np.sort(lending_co_data_numeric,axis=0)

array([[ 1000.,    35.,   365., -2870., -2870.,  -350.],
       [ 1000.,    35.,   365., -2550., -2100.,   150.],
       [ 1000.,    35.,   365., -2450., -2000.,  1100.],
       ...,
       [ 9000.,   125.,   365., 16751., 18751., 54625.],
       [ 9000.,   165.,   365., 17650., 20001., 54625.],
       [ 9000.,   165.,   365., 19001., 22001., 64001.]], shape=(1043, 6))

In [104]:
np.argsort(lending_co_data_numeric,axis=0)

array([[1041,  816, 1039,   32,   32,  482],
       [  22,  432, 1038,  166,  166,  493],
       [  23,  443, 1037,   85,   85,  166],
       ...,
       [ 978,  152, 1041,  568, 1019,  568],
       [ 193,   27, 1042,  718, 1033,  953],
       [ 202,  408,    0,  912,  912,   27]], shape=(1043, 6))

In [105]:
lending_co_data_numeric[482,5]

np.float64(-350.0)

In [109]:
lending_co_data_numeric=lending_co_data_numeric[np.argsort(lending_co_data_numeric[:,0])]
lending_co_data_numeric

array([[ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 1000.,    50.,   365.,  1400.,  2550., 12700.],
       [ 1000.,    40.,   365.,  2240.,  4560., 14520.],
       ...,
       [ 9000.,   125.,   365., 12126., 15251., 45626.],
       [ 9000.,   125.,   365., 12001., 15751., 38626.],
       [ 9000.,   125.,   365., 13001., 17001., 54625.]], shape=(1043, 6))

In [110]:
lending_co_data_numeric.argsort(axis=0)

array([[   0,  184, 1039,  213,  213,  128],
       [   1,  149, 1038,  113,  113,  131],
       [   2,  141, 1037,   35,   35,  113],
       ...,
       [1042, 1040, 1041, 1026, 1034, 1026],
       [1028, 1023, 1042,  922, 1037, 1022],
       [1027, 1025,    0, 1038, 1038, 1025]], shape=(1043, 6))

6. np.argwhere
   Goes over the entire NDarray and checks whether the inidvidual elements satisfy a given condition.The outputs are  the indices for all the individual elements where the condition is met.The default conndition is to check for values different from 0.

In [111]:
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric.csv"
lending_co_data_numeric=np.loadtxt(filename,delimiter=',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [112]:
np.argwhere(lending_co_data_numeric)

array([[   0,    0],
       [   0,    1],
       [   0,    2],
       ...,
       [1042,    3],
       [1042,    4],
       [1042,    5]], shape=(6256, 2))

In [113]:
np.argwhere(lending_co_data_numeric==False)

array([[116,   4],
       [430,   3]])

In [114]:
#this means there are 2 zeros at the position(116,4) and (430,3)


In [115]:
lending_co_data_numeric[116,4]

np.float64(0.0)

In [116]:
lending_co_data_numeric[430,3]

np.float64(0.0)

In [117]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [118]:
np.argwhere(lending_co_data_numeric>1000)

array([[   0,    0],
       [   0,    3],
       [   0,    4],
       ...,
       [1042,    3],
       [1042,    4],
       [1042,    5]], shape=(3813, 2))

In [119]:
np.argwhere(lending_co_data_numeric%2==0)

array([[   0,    0],
       [   0,    1],
       [   1,    0],
       ...,
       [1042,    0],
       [1042,    1],
       [1042,    5]], shape=(4183, 2))

In [122]:
#combining isnan() and np.argwhere
import numpy as np
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric-NAN.csv"
lending_co_data_nan=np.genfromtxt(filename,delimiter=';')
lending_co_data_nan

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [123]:
np.isnan(lending_co_data_nan)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]], shape=(1043, 6))

In [125]:
np.argwhere(np.isnan(lending_co_data_nan))  #this will give indices of zero values.

array([[  11,    3],
       [  15,    3],
       [  27,    3],
       [  58,    3],
       [  60,    4],
       [  85,    4],
       [ 117,    5],
       [ 152,    1],
       [ 152,    2],
       [ 152,    4],
       [ 172,    1],
       [ 175,    1],
       [ 175,    2],
       [ 176,    3],
       [ 177,    4],
       [ 178,    5],
       [ 211,    3],
       [ 229,    0],
       [ 230,    1],
       [ 237,    1],
       [ 247,    3],
       [ 251,    5],
       [ 252,    4],
       [ 258,    1],
       [ 260,    3],
       [ 262,    4],
       [ 271,    5],
       [ 272,    4],
       [ 284,    2],
       [ 284,    3],
       [ 297,    1],
       [ 297,    2],
       [ 300,    3],
       [ 315,    3],
       [ 315,    5],
       [ 327,    4],
       [ 336,    4],
       [ 343,    0],
       [ 344,    2],
       [ 346,    2],
       [ 363,    3],
       [ 375,    3],
       [ 377,    2],
       [ 398,    5],
       [ 416,    4],
       [ 428,    0],
       [ 432,    1],
       [ 433,

In [127]:
lending_co_data_nan[11,3]  #true

np.float64(nan)

In [128]:
#handle missing values by using np.argwhere
for array_index in np.argwhere(np.isnan(lending_co_data_nan)):
    lending_co_data_nan[array_index[0],array_index[1]]=0
    

In [129]:
lending_co_data_nan[11,3]

np.float64(0.0)

In [131]:
np.isnan(lending_co_data_nan).sum()

np.int64(0)

7.shuffling
Rearranging the parts of a dataset.We do so without a fixed pattern.The end goal is that a random sample would be representative of the enitire dataset.

In [132]:
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric.csv"
lending_co_data_numeric=np.loadtxt(filename,delimiter=',')[:8]
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

In [133]:
np.random.shuffle(lending_co_data_numeric)   #it will replace the original dataset

In [134]:
lending_co_data_numeric

array([[ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 2000.,    40.,   365.,  3121.,  4241., 13621.]])

In [135]:
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric.csv"
lending_co_data_numeric=np.loadtxt(filename,delimiter=',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [136]:
from numpy.random import shuffle

In [137]:
shuffle(lending_co_data_numeric)
lending_co_data_numeric

array([[ 1000.,    50.,   365.,  -300.,   200.,  8918.],
       [ 2000.,    40.,   365.,  3701.,  4301., 10201.],
       [ 2000.,    40.,   365.,  3121.,  5161., 13441.],
       ...,
       [ 2000.,    40.,   365.,  3121.,  5381., 15281.],
       [ 9000.,   165.,   365., 14501., 16846., 64001.],
       [ 1000.,    40.,   365.,  3060.,  4060., 15600.]], shape=(1043, 6))

In [138]:
#shuffling using random generators.

from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg
array_RG=gen(pcg())   #if we give seed also then also it will not give same shuffling.
array_RG.shuffle(lending_co_data_numeric)

In [139]:
lending_co_data_numeric

array([[ 2000.,    50.,   365.,  3750.,  5250., 20250.],
       [ 4000.,    50.,   365., 14500., 14500., 21650.],
       [ 4000.,    50.,   365.,  5400.,  6700., 19830.],
       ...,
       [ 2000.,    40.,   365.,  3401.,  4261., 16600.],
       [ 4000.,    50.,   365.,  7000.,  7000., 22250.],
       [ 2000.,    40.,   365.,  3321.,  4421., 15791.]], shape=(1043, 6))

8.Assigning Types(casting Nd arrays)
Taking an object with values of a certain datatype and creatimg an identical object that contains values of a different datatype.

In [140]:
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric.csv"
lending_co_data_numeric=np.loadtxt(filename,delimiter=',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [141]:
lending_co_data_numeric.astype(dtype=np.int32)  #decimals to integers

array([[ 2000,    40,   365,  3121,  4241, 13621],
       [ 2000,    40,   365,  3061,  4171, 15041],
       [ 1000,    40,   365,  2160,  3280, 15340],
       ...,
       [ 2000,    40,   365,  4201,  5001, 16600],
       [ 1000,    40,   365,  2080,  3320, 15600],
       [ 2000,    40,   365,  4601,  4601, 16600]],
      shape=(1043, 6), dtype=int32)

In [142]:
#operations on a string array:
# 1. first we are creating a string array


In [147]:
lending_co_data_numeric=lending_co_data_numeric.astype(dtype=str)
lending_co_data_numeric


array([['2000.0', '40.0', '365.0', '3121.0', '4241.0', '13621.0'],
       ['2000.0', '40.0', '365.0', '3061.0', '4171.0', '15041.0'],
       ['1000.0', '40.0', '365.0', '2160.0', '3280.0', '15340.0'],
       ...,
       ['2000.0', '40.0', '365.0', '4201.0', '5001.0', '16600.0'],
       ['1000.0', '40.0', '365.0', '2080.0', '3320.0', '15600.0'],
       ['2000.0', '40.0', '365.0', '4601.0', '4601.0', '16600.0']],
      shape=(1043, 6), dtype='<U32')

In [148]:
lending_co_data_numeric=lending_co_data_numeric.astype(dtype=np.int32)
lending_co_data_numeric  #we can't directly convert string to int

ValueError: invalid literal for int() with base 10: np.str_('2000.0')

In [149]:
#so first convert to decimal then int32

In [152]:
lending_co_data_numeric=lending_co_data_numeric.astype(dtype=np.float32)
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]],
      shape=(1043, 6), dtype=float32)

In [153]:
lending_co_data_numeric=lending_co_data_numeric.astype(dtype=np.int32)
lending_co_data_numeric

array([[ 2000,    40,   365,  3121,  4241, 13621],
       [ 2000,    40,   365,  3061,  4171, 15041],
       [ 1000,    40,   365,  2160,  3280, 15340],
       ...,
       [ 2000,    40,   365,  4201,  5001, 16600],
       [ 1000,    40,   365,  2080,  3320, 15600],
       [ 2000,    40,   365,  4601,  4601, 16600]],
      shape=(1043, 6), dtype=int32)

In [154]:
#Another method for converting string to int.

filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric.csv"
lending_co_data_numeric=np.loadtxt(filename,delimiter=',')
lending_co_data_numeric=lending_co_data_numeric.astype(dtype=str)
lending_co_data_numeric

array([['2000.0', '40.0', '365.0', '3121.0', '4241.0', '13621.0'],
       ['2000.0', '40.0', '365.0', '3061.0', '4171.0', '15041.0'],
       ['1000.0', '40.0', '365.0', '2160.0', '3280.0', '15340.0'],
       ...,
       ['2000.0', '40.0', '365.0', '4201.0', '5001.0', '16600.0'],
       ['1000.0', '40.0', '365.0', '2080.0', '3320.0', '15600.0'],
       ['2000.0', '40.0', '365.0', '4601.0', '4601.0', '16600.0']],
      shape=(1043, 6), dtype='<U32')

In [155]:
lending_co_data_numeric.astype(dtype=np.float32).astype(dtype=np.int32)  #it will not chnage original nd array

array([[ 2000,    40,   365,  3121,  4241, 13621],
       [ 2000,    40,   365,  3061,  4171, 15041],
       [ 1000,    40,   365,  2160,  3280, 15340],
       ...,
       [ 2000,    40,   365,  4201,  5001, 16600],
       [ 1000,    40,   365,  2080,  3320, 15600],
       [ 2000,    40,   365,  4601,  4601, 16600]],
      shape=(1043, 6), dtype=int32)

In [156]:
lending_co_data_numeric

array([['2000.0', '40.0', '365.0', '3121.0', '4241.0', '13621.0'],
       ['2000.0', '40.0', '365.0', '3061.0', '4171.0', '15041.0'],
       ['1000.0', '40.0', '365.0', '2160.0', '3280.0', '15340.0'],
       ...,
       ['2000.0', '40.0', '365.0', '4201.0', '5001.0', '16600.0'],
       ['1000.0', '40.0', '365.0', '2080.0', '3320.0', '15600.0'],
       ['2000.0', '40.0', '365.0', '4601.0', '4601.0', '16600.0']],
      shape=(1043, 6), dtype='<U32')

8.Stripping Data

In [158]:
import numpy as np
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-Company-Total-Price.csv"
lending_co_total_price=np.genfromtxt(filename,delimiter=',',dtype=str,skip_header=1,usecols=[1,2,4])
lending_co_total_price

array([['id_1', 'Product B', 'Location 2'],
       ['id_2', 'Product B', 'Location 3'],
       ['id_3', 'Product C', 'Location 5'],
       ...,
       ['id_413', 'Product B', 'Location 135'],
       ['id_414', 'Product C', 'Location 200'],
       ['id_415', 'Product A', 'Location 8']],
      shape=(415, 3), dtype='<U12')

In [165]:
lending_co_total_price[:,0]=np.chararray.strip(lending_co_total_price[:,0],"id_")
lending_co_total_price[:,1]=np.chararray.strip(lending_co_total_price[:,1],"Product ")
lending_co_total_price[:,2]=np.chararray.strip(lending_co_total_price[:,2],"Location ")
lending_co_total_price

C:\Users\ASUS\AppData\Local\Temp\ipykernel_28568\359225589.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  lending_co_total_price[:,0]=np.chararray.strip(lending_co_total_price[:,0],"id_")
C:\Users\ASUS\AppData\Local\Temp\ipykernel_28568\359225589.py:2: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  lending_co_total_price[:,1]=np.chararray.strip(lending_co_total_price[:,1],"Product ")
C:\Users\ASUS\AppData\Local\Temp\ipykernel_28568\359225589.py:3: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  lending_co_total_price[:,2]=np.chararray.strip(lending_co_total_price[:,2],"Location ")


array([['1', 'B', '2'],
       ['2', 'B', '3'],
       ['3', 'C', '5'],
       ...,
       ['413', 'B', '135'],
       ['414', 'C', '200'],
       ['415', 'A', '8']], shape=(415, 3), dtype='<U12')

In [170]:
#for coducting quantitative analysis we need to convert the alphabets in the second column to integers
# we can use np.where
## First, convert the array to object dtype to handle mixed types
lending_co_total_price = lending_co_total_price.astype(object)

In [171]:
lending_co_total_price[:,1]=np.where(lending_co_total_price[:,1]=='A',1,lending_co_total_price[:,1])
lending_co_total_price[:,1]=np.where(lending_co_total_price[:,1]=='B',2,lending_co_total_price[:,1])
lending_co_total_price[:,1]=np.where(lending_co_total_price[:,1]=='C',3,lending_co_total_price[:,1])
lending_co_total_price[:,1]=np.where(lending_co_total_price[:,1]=='D',4,lending_co_total_price[:,1])
lending_co_total_price[:,1]=np.where(lending_co_total_price[:,1]=='E',5,lending_co_total_price[:,1])
lending_co_total_price[:,1]=np.where(lending_co_total_price[:,1]=='F',6,lending_co_total_price[:,1])
lending_co_total_price

array([['1', 2, '2'],
       ['2', 2, '3'],
       ['3', 3, '5'],
       ...,
       ['413', 2, '135'],
       ['414', 3, '200'],
       ['415', 1, '8']], shape=(415, 3), dtype=object)

In [174]:

lending_co_total_price = lending_co_total_price.astype(dtype=np.int32)
lending_co_total_price

array([[  1,   2,   2],
       [  2,   2,   3],
       [  3,   3,   5],
       ...,
       [413,   2, 135],
       [414,   3, 200],
       [415,   1,   8]], shape=(415, 3), dtype=int32)

9.Stacking Data in Nd array:placing multiple objects on top of one another to create a bigger object.we can just stack arrays of matching shapes to create a larger array-a "stack" 

 np.stack
 np.vstack
 np.hstack
 np.dstack


In [175]:
import numpy as np
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric.csv"
lending_co_data_numeric=np.loadtxt(filename,delimiter=',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [184]:
import numpy as np
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric-NAN.csv"
lending_co_data_numeric_nan=np.genfromtxt(filename,delimiter=';')
lending_co_data_numeric_nan
temporary_fill=np.nanmax(lending_co_data_numeric_nan).round(2)+1
temporary_mean=np.nanmean(lending_co_data_numeric_nan,axis=0).round(2)
lending_co_data_numeric_nan=np.genfromtxt(filename,delimiter=';',filling_values=temporary_fill)
for i in range (lending_co_data_numeric_nan.shape[1]):
    lending_co_data_numeric_nan[:,i]=np.where(lending_co_data_numeric_nan[:,i]==temporary_fill,
                                              temporary_mean[i],lending_co_data_numeric_nan[:,i])
lending_co_data_numeric_nan

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]],
      shape=(1043, 6))

In [186]:
#just arrange the first given column as first row...and so on....
np.stack((lending_co_data_numeric_nan[:,0],lending_co_data_numeric_nan[:,1]))

array([[2000.  , 2000.  , 1000.  , ..., 2250.25, 1000.  , 2000.  ],
       [  40.  ,   40.  ,   40.  , ...,   40.  ,   40.  ,   40.  ]],
      shape=(2, 1043))

In [187]:
np.stack((lending_co_data_numeric_nan[:,1],lending_co_data_numeric_nan[:,0]))

array([[  40.  ,   40.  ,   40.  , ...,   40.  ,   40.  ,   40.  ],
       [2000.  , 2000.  , 1000.  , ..., 2250.25, 1000.  , 2000.  ]],
      shape=(2, 1043))

In [189]:
#column wise output
np.stack((lending_co_data_numeric_nan[:,0],lending_co_data_numeric_nan[:,1]),axis=1)

array([[2000.  ,   40.  ],
       [2000.  ,   40.  ],
       [1000.  ,   40.  ],
       ...,
       [2250.25,   40.  ],
       [1000.  ,   40.  ],
       [2000.  ,   40.  ]], shape=(1043, 2))

In [191]:
#stacking multiple objects
np.stack((lending_co_data_numeric_nan[:,0],lending_co_data_numeric_nan[:,1],lending_co_data_numeric_nan[:,2]),axis=1)



array([[2000.  ,   40.  ,  365.  ],
       [2000.  ,   40.  ,  365.  ],
       [1000.  ,   40.  ,  365.  ],
       ...,
       [2250.25,   40.  ,  365.  ],
       [1000.  ,   40.  ,  365.  ],
       [2000.  ,   40.  ,  365.  ]], shape=(1043, 3))

In [192]:
#np.vstack, np.hstack,np.dstack they are used to stack matrices.
#stacking lending_co_data_numeric and lending_co_data_numeric_nan
#these are going to be stacked


In [193]:
#vstack means vertical stack....the fn stacks 2-D arrays vertically.places the first 
#array on top of the second one.results in longer array

In [194]:
np.vstack((lending_co_data_numeric,lending_co_data_numeric_nan))


array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]],
      shape=(2086, 6))

In [196]:
#horizontal stack.....
np.hstack((lending_co_data_numeric,lending_co_data_numeric_nan))

array([[ 2000.,    40.,   365., ...,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365., ...,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365., ...,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365., ...,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365., ...,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365., ...,  4601.,  4601., 16600.]],
      shape=(1043, 12))

In [197]:
#np.dstack:= depth stack...we stack arrays in the third dimension.returns an array of higher 
#dimension.

In [198]:
np.dstack((lending_co_data_numeric,lending_co_data_numeric_nan))

array([[[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 3121.  ,  3121.  ],
        [ 4241.  ,  4241.  ],
        [13621.  , 13621.  ]],

       [[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 3061.  ,  3061.  ],
        [ 4171.  ,  4171.  ],
        [15041.  , 15041.  ]],

       [[ 1000.  ,  1000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 2160.  ,  2160.  ],
        [ 3280.  ,  3280.  ],
        [15340.  , 15340.  ]],

       ...,

       [[ 2000.  ,  2250.25],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 4201.  ,  4201.  ],
        [ 5001.  ,  5001.  ],
        [16600.  , 16600.  ]],

       [[ 1000.  ,  1000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 2080.  ,  2080.  ],
        [ 3320.  ,  3320.  ],
        [15600.  , 15600.  ]],

       [[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  

In [202]:
np.dstack((lending_co_data_numeric,lending_co_data_numeric_nan))[0] #each column contains first row

array([[ 2000.,  2000.],
       [   40.,    40.],
       [  365.,   365.],
       [ 3121.,  3121.],
       [ 4241.,  4241.],
       [13621., 13621.]])

In [203]:
np.dstack((lending_co_data_numeric,lending_co_data_numeric_nan))[0][0] #first row first coulmn

array([2000., 2000.])

In [204]:
np.dstack((lending_co_data_numeric,lending_co_data_numeric_nan))[0,:,0] #row,column,array

array([ 2000.,    40.,   365.,  3121.,  4241., 13621.])

10.Concatenate

In [ ]:
Linking together objects in a chain.Creating a new(larger)array by merging existing smaller 
arrays along a given axis.The inputs and the outputs of the np.concatenate() function always 
have the same number of dimensions.


In [205]:
import numpy as np
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric.csv"
lending_co_data_numeric=np.loadtxt(filename,delimiter=',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [206]:
#concatenating first 2 rows.

In [208]:
np.concatenate((lending_co_data_numeric[0,:],lending_co_data_numeric[1,:]))

array([ 2000.,    40.,   365.,  3121.,  4241., 13621.,  2000.,    40.,
         365.,  3061.,  4171., 15041.])

In [209]:
#it is similar to stacking but here it returns 1D array

In [210]:
#concatenating 2d arrays

In [211]:
import numpy as np
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric-NAN.csv"
lending_co_data_numeric_nan=np.genfromtxt(filename,delimiter=';')
lending_co_data_numeric_nan
temporary_fill=np.nanmax(lending_co_data_numeric_nan).round(2)+1
temporary_mean=np.nanmean(lending_co_data_numeric_nan,axis=0).round(2)
lending_co_data_numeric_nan=np.genfromtxt(filename,delimiter=';',filling_values=temporary_fill)
for i in range (lending_co_data_numeric_nan.shape[1]):
    lending_co_data_numeric_nan[:,i]=np.where(lending_co_data_numeric_nan[:,i]==temporary_fill,
                                              temporary_mean[i],lending_co_data_numeric_nan[:,i])
lending_co_data_numeric_nan

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]],
      shape=(1043, 6))

In [212]:
#it is similar to hstack
np.concatenate((lending_co_data_numeric,lending_co_data_numeric_nan))

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]],
      shape=(2086, 6))

In [214]:
#concatenating through columns...
np.concatenate((lending_co_data_numeric,lending_co_data_numeric_nan),axis=1)

array([[ 2000.,    40.,   365., ...,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365., ...,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365., ...,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365., ...,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365., ...,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365., ...,  4601.,  4601., 16600.]],
      shape=(1043, 12))

np.concatenate works exactly like np.hstack(),np.vstack(),np.dstack() depending on the inputs and axis arguments.
1&2-D arrays:
np.hstack()->np.concatenate((),axis=0)
np.vstack()->np.concatenate((),axis=1)
np.dstack()->np.concatenate((),axis=2)

In [215]:
np.concatenate((lending_co_data_numeric[0,:],lending_co_data_numeric[:,0]))

array([2000.,   40.,  365., ..., 2000., 1000., 2000.], shape=(1049,))

However if we have arrays of the same dimensions,but different shapes,we can still concatenate them.But only if their dimensions match for the axis we are concatenating along.

11.finding unique values

In [216]:
import numpy as np
filename=r"D:\dataanalyst\Data Analyst Course\S27 - NumPy Preprocessing\Lending-company-Numeric.csv"
lending_co_data_numeric=np.loadtxt(filename,delimiter=',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [217]:
np.unique(lending_co_data_numeric)

array([-2870., -2550., -2450., ..., 52751., 54625., 64001.], shape=(1140,))

In [219]:
np.unique(lending_co_data_numeric[:,1])
#returns array of unique values from second column...in ascending order

array([ 35.,  40.,  50., 125., 165.])

In [220]:
#in the case of strings it works same....based on ascii value it sorts.

In [221]:
np.unique(lending_co_data_numeric[:,1],return_counts=True)
#first array gives unique values....and second will give their frequency.

(array([ 35.,  40.,  50., 125., 165.]), array([  4, 567, 451,  19,   2]))

In [222]:
np.unique(lending_co_data_numeric[:,1],return_counts=True,return_index=True)
#first array gives unique values....and second will give their index....the third will give 
#the frequency

(array([ 35.,  40.,  50., 125., 165.]),
 array([327,   0,   4,  19,  27]),
 array([  4, 567, 451,  19,   2]))