In [18]:
import numpy as np

In [175]:
#suppress=True  :=to convert scientific notations to normal one
#linewidth=100  :=100 characters in a line.
#precision=2 :only 2 decimal numbers after point.
np.set_printoptions(suppress=True,linewidth=100,precision=2)

In [3]:
filename=r"D:\dataanalyst\Data Analyst Course\S28 - A Loan Data Example with NumPy\loan-data.csv"
raw_data_np=np.genfromtxt(filename,delimiter=';',skip_header=1,autostrip=True)
raw_data_np
#here first when we printed it has column names .since they are strings they showed as nan .
#so to remove them we use skip_header=1
#to remove unecessary whitespaces we use autostrip=True.

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]],
      shape=(10000, 14))

# Checking for incomplete data

In [4]:
np.isnan(raw_data_np).sum()

np.int64(88005)

In [5]:
temporary_fill=np.nanmax(raw_data_np).round(2)+1
temporary_mean=np.nanmean(raw_data_np,axis=0).round(2)


C:\Users\ASUS\AppData\Local\Temp\ipykernel_4160\3766350492.py:2: RuntimeWarning: Mean of empty slice
  temporary_mean=np.nanmean(raw_data_np,axis=0).round(2)


In [6]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [7]:
temporary_stats=np.array([np.nanmin(raw_data_np,axis=0),
                          temporary_mean,
                          np.nanmax(raw_data_np,axis=0)])

C:\Users\ASUS\AppData\Local\Temp\ipykernel_4160\1435060183.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats=np.array([np.nanmin(raw_data_np,axis=0),
C:\Users\ASUS\AppData\Local\Temp\ipykernel_4160\1435060183.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np,axis=0)])


In [8]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

# splitting the dataset

we need to find the indices where string and numeric datas are there in temporary_mean
we are doing this because we handle the missing values among string and numbers differently.

In [10]:
column_strings=np.argwhere(np.isnan(temporary_mean)).squeeze()
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [11]:
column_numeric=np.argwhere(np.isnan(temporary_mean)==False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13])

# Reimporting the dataset

In [12]:
loan_data_strings=np.genfromtxt(filename,delimiter=';',
                                skip_header=1,
                                autostrip=True,
                                usecols=column_strings,
                                dtype=str)
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      shape=(10000, 8), dtype='<U69')

In [13]:
loan_data_numeric=np.genfromtxt(filename,delimiter=';',
                                skip_header=1,
                                autostrip=True,
                                usecols=column_numeric,
                                filling_values=temporary_fill
                               )
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]],
      shape=(10000, 6))

we are going to work like these .....separately. we need to add the columns names also.

# The names of the columns

In [14]:
header_full=np.genfromtxt(filename,delimiter=';',skip_footer=raw_data_np.shape[0],
                          autostrip=True,dtype=str)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [15]:
header_strings,header_numeric=header_full[column_strings],header_full[column_numeric]


In [16]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [17]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# creating checkpoints

In [19]:
def checkpoint(file_name,checkpoint_header,checkpoint_data):
    np.savez(file_name,header=checkpoint_header,data=checkpoint_data)
    checkpoint_variable=np.load(file_name+".npz")
    return(checkpoint_variable)
    

In [20]:
checkpoint_test=checkpoint("checkpoint-test",header_strings,loan_data_strings)

In [21]:
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [22]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      shape=(10000, 8), dtype='<U69')

# Manipulating Text data /manipulating string columns

In [23]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [24]:
header_strings[0]="issue_date"

In [25]:
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      shape=(10000, 8), dtype='<U69')

# 1.issue date

In [26]:

loan_data_strings[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], shape=(10000,), dtype='<U69')

In [27]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [28]:
loan_data_strings[:,0]=np.chararray.strip(loan_data_strings[:,0],"-15")

C:\Users\ASUS\AppData\Local\Temp\ipykernel_4160\151724122.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  loan_data_strings[:,0]=np.chararray.strip(loan_data_strings[:,0],"-15")


In [29]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [30]:
# we need to represent months by integers...for that...

In [31]:
months=np.array(["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"])

In [32]:
loan_data_strings=loan_data_strings.astype(object)
#it is done bcoz python cannot convert strings to int directly..so giving i it is done

In [33]:
for i in range(13):
    loan_data_strings[:,0]=np.where(loan_data_strings[:,0]==months[i],
                                    i,
                                    loan_data_strings[:,0])

In [34]:
np.unique(loan_data_strings[:,0])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], dtype=object)

In [35]:
#the missing value is filled with 0

# 2.Loan status

In [36]:
loan_data_strings[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'],
      shape=(10000,), dtype=object)

In [37]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype=object)

Regressions only care if the candidate is in a stable financial condition.
we can use np.where() to assign a different number to each one.
we need to split all possible values into either group(good vs bad)
good(1):- current,fully paid,in grace period,issued,less than a month late
bad(0):-chargedoff,default,missing value,late more than a month.

In [39]:
status_bad=np.array(["","Charged Off","Default","Late (31-120 days)"])
status_good=np.array(["Current","Fully Paid","In Grace Period","Issued","Late (16-30 days)"])

In [40]:
loan_data_strings[:,1]=np.where(np.isin(loan_data_strings[:,1],status_bad),0,1)

In [41]:
loan_data_strings[:,1]

array([1, 1, 1, ..., 1, 1, 1], shape=(10000,), dtype=object)

In [42]:
np.unique(loan_data_strings[:,1])

array([0, 1], dtype=object)

# 3.Term

In [43]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [44]:
loan_data_strings[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      shape=(10000,), dtype=object)

In [45]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype=object)

In [46]:
loan_data_strings = loan_data_strings.astype(str)

In [47]:
loan_data_strings[:,2]=np.chararray.strip(loan_data_strings[:,2]," months")


C:\Users\ASUS\AppData\Local\Temp\ipykernel_4160\508369555.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  loan_data_strings[:,2]=np.chararray.strip(loan_data_strings[:,2]," months")


In [48]:
np.unique(loan_data_strings[:,2])

array(['', '36', '60'], dtype='<U69')

i need to change the name of the column from term to term_months to make it descriptive.


In [49]:
header_strings[2]="term_months"

we need to fill the empty space.in a CRM(credit risk modelling) we always assumes worst for missing values.

In [50]:
loan_data_strings[:,2]=np.where(loan_data_strings[:,2]=="",'60',loan_data_strings[:,2])

In [51]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

# 4.Grades

In [52]:
header_strings[3]

np.str_('grade')

In [53]:
loan_data_strings[:,3]

array(['C', 'A', 'B', ..., 'A', 'D', 'A'], shape=(10000,), dtype='<U69')

In [54]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [55]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

# Filling subgrades

In [56]:
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4]=np.where((loan_data_strings[:,4]=="")&(loan_data_strings[:,3]==i),
                                    i+"5",
                                    loan_data_strings[:,4]
                                   )

In [59]:
np.unique(loan_data_strings[:,4],return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

In [ ]:
# we need to create separate category for missing values...so H1

In [60]:
loan_data_strings[:,4]=np.where(loan_data_strings[:,4]=="","H1",loan_data_strings[:,4])

In [61]:
np.unique(loan_data_strings[:,4],return_counts=True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9]))

# Removing grades

In [62]:
loan_data_strings=np.delete(loan_data_strings,3,axis=1)


In [64]:
header_strings=np.delete(header_strings,3)

In [65]:
loan_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], shape=(10000,), dtype='<U69')

In [66]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

# converting subgrades

In [67]:
np.unique(loan_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [71]:
keys=list(np.unique(loan_data_strings[:,3]))
values=list(range(1,np.unique(loan_data_strings[:,3]).shape[0]+1))
dict_sub_grade=dict(zip(keys,values))

In [73]:
dict_sub_grade

{np.str_('A1'): 1,
 np.str_('A2'): 2,
 np.str_('A3'): 3,
 np.str_('A4'): 4,
 np.str_('A5'): 5,
 np.str_('B1'): 6,
 np.str_('B2'): 7,
 np.str_('B3'): 8,
 np.str_('B4'): 9,
 np.str_('B5'): 10,
 np.str_('C1'): 11,
 np.str_('C2'): 12,
 np.str_('C3'): 13,
 np.str_('C4'): 14,
 np.str_('C5'): 15,
 np.str_('D1'): 16,
 np.str_('D2'): 17,
 np.str_('D3'): 18,
 np.str_('D4'): 19,
 np.str_('D5'): 20,
 np.str_('E1'): 21,
 np.str_('E2'): 22,
 np.str_('E3'): 23,
 np.str_('E4'): 24,
 np.str_('E5'): 25,
 np.str_('F1'): 26,
 np.str_('F2'): 27,
 np.str_('F3'): 28,
 np.str_('F4'): 29,
 np.str_('F5'): 30,
 np.str_('G1'): 31,
 np.str_('G2'): 32,
 np.str_('G3'): 33,
 np.str_('G4'): 34,
 np.str_('G5'): 35,
 np.str_('H1'): 36}

In [76]:
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3]=np.where(loan_data_strings[:,3]==i,
                                    str(dict_sub_grade[i]),
                                    loan_data_strings[:,3])

In [77]:
np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

# verification status

In [78]:
loan_data_strings[:,4]

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
      shape=(10000,), dtype='<U69')

In [79]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [82]:
loan_data_strings[:,4]=np.where((loan_data_strings[:,4]=="")|(loan_data_strings[:,4]=="Not Verified"),0,1)

In [83]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

# URL

In [84]:
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'],
      shape=(10000,), dtype='<U69')

In [85]:
np.chararray.strip(loan_data_strings[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

C:\Users\ASUS\AppData\Local\Temp\ipykernel_4160\351693894.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  np.chararray.strip(loan_data_strings[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")


array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
      shape=(10000,), dtype='<U69')

In [87]:
loan_data_strings[:,5]=np.chararray.strip(loan_data_strings[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

C:\Users\ASUS\AppData\Local\Temp\ipykernel_4160\1777435056.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  loan_data_strings[:,5]=np.chararray.strip(loan_data_strings[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")


In [88]:
loan_data_strings[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
      shape=(10000,), dtype='<U69')

In [92]:
loan_data_numeric[:,0].astype(dtype=np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249],
      shape=(10000,), dtype=int32)

In [93]:
loan_data_strings[:,5].astype(dtype=np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249],
      shape=(10000,), dtype=int32)

In [94]:
np.array_equal(loan_data_numeric[:,0].astype(dtype=np.int32),loan_data_strings[:,5].astype(dtype=np.int32))

True

In [116]:
#since URL holds same as loan_id we will delete url


In [ ]:
loan_data_strings=np.delete(loan_data_strings,5,axis=1)
header_strings=np.delete(header_strings,5)

In [117]:
loan_data_strings


array([['5', '1', '36', '13', '1', 'CA'],
       ['0', '1', '36', '5', '1', 'NY'],
       ['9', '1', '36', '10', '1', 'PA'],
       ...,
       ['6', '1', '36', '5', '1', 'CA'],
       ['4', '1', '36', '17', '1', 'OH'],
       ['12', '1', '36', '4', '0', 'IL']], shape=(10000, 6), dtype='<U69')

# State Address

In [118]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [120]:
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], shape=(10000,), dtype='<U69')

In [122]:
np.unique(loan_data_strings[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [123]:
np.unique(loan_data_strings[:,5]).size

50

In [124]:
np.unique(loan_data_strings[:,5],return_counts=True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27]))

In [125]:
states_names,states_count=np.unique(loan_data_strings[:,5],return_counts=True)

In [126]:
states_count_sorted=np.argsort(-states_count)

In [127]:
states_names[states_count_sorted],states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'TN', 'CT', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DC', 'DE', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

In [129]:
loan_data_strings[:,5]=np.where(loan_data_strings[:,5]=="",'0',loan_data_strings[:,5])

In [130]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [133]:
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5],states_west),'1',loan_data_strings[:,5])
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5],states_south),'2',loan_data_strings[:,5])
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5],states_midwest),'3',loan_data_strings[:,5])
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5],states_east),'4',loan_data_strings[:,5])

In [135]:
np.unique(loan_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

# Converting to numbers

In [136]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], shape=(10000, 6), dtype='<U69')

In [139]:
loan_data_strings=loan_data_strings.astype(dtype=np.int32)

In [140]:
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], shape=(10000, 6), dtype=int32)

# checkpoint1:Strings

In [142]:
checkpoint_strings=checkpoint("checkpoint-strings",header_strings,loan_data_strings)

In [143]:
checkpoint_strings

NpzFile 'checkpoint-strings.npz' with keys: header, data

In [144]:
checkpoint_strings["header"]

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [145]:
checkpoint_strings["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], shape=(10000, 6), dtype=int32)

# manipulating numeric values

In [146]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]],
      shape=(10000, 6))

In [147]:
np.isnan(loan_data_numeric).sum()

np.int64(0)

In [148]:
#it is zero because when we split the dataset we filled with temporary_filling.we need to fill those
#with worst case.

# Substitute filler values.

In [149]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# ID

In [150]:
temporary_fill

np.float64(68616520.0)

In [151]:
np.isin(loan_data_numeric[:,0],temporary_fill)

array([False, False, False, ..., False, False, False], shape=(10000,))

In [152]:
np.isin(loan_data_numeric[:,0],temporary_fill).sum()

np.int64(0)

In [ ]:
#since it is zero we dont need to fill any values.

# Temporary Stats

In [159]:
temporary_stats[:,column_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

# Funded amount

In [156]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.], shape=(10000,))

In [160]:
loan_data_numeric[:,2]=np.where(loan_data_numeric[:,2]==temporary_fill,
                                temporary_stats[0,column_numeric[2]],
                                loan_data_numeric[:,2])

In [161]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.], shape=(10000,))

In [164]:
temporary_stats[0,column_numeric[3]]

np.float64(6.0)

# Loan amount,interest rate,total payment,installment

In [166]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [167]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i]=np.where(loan_data_numeric[:,i]==temporary_fill,
                                    temporary_stats[2,column_numeric[i]],
                                    loan_data_numeric[:,i]
                                   )

In [168]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]],
      shape=(10000, 6))

# Currency Change

Convert dollars to euros

In [181]:
filename1=r"D:\dataanalyst\Data Analyst Course\S28 - A Loan Data Example with NumPy\EUR-USD.csv"
EUR_USD=np.genfromtxt(filename1,delimiter=',',autostrip=True,skip_header=1,usecols=3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [182]:
loan_data_strings[:,0]

array([ 5,  0,  9, ...,  6,  4, 12], shape=(10000,), dtype=int32)

In [183]:
exchange_rate=loan_data_strings[:,0]


In [184]:
for i in range(1,13):
    exchange_rate=np.where(exchange_rate==i,
                           EUR_USD[i-1],
                           exchange_rate)
exchange_rate=np.where(exchange_rate==0,
                       np.mean(EUR_USD),
                       exchange_rate)
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09], shape=(10000,))

In [185]:
exchange_rate.shape

(10000,)

In [186]:
loan_data_numeric.shape

(10000, 6)

In [187]:
exchange_rate=np.reshape(exchange_rate,(10000,1))

In [188]:
loan_data_numeric=np.hstack((loan_data_numeric,exchange_rate))

In [191]:
header_numeric=np.concatenate((header_numeric,np.array(["exchange_rate"])))

In [192]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

Currency change from USD to EUR

In [194]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [195]:
column_dollar=np.array([1,2,4,5])

In [197]:
loan_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09], shape=(10000,))

In [198]:
for i in column_dollar:
    loan_data_numeric=np.hstack((loan_data_numeric,np.reshape(loan_data_numeric[:,i]/loan_data_numeric[:,6],(10000,1))))
    

In [199]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]],
      shape=(10000, 11))

# Expanding the header

In [201]:
header_additional=np.array([column_name+"_EUR" for column_name in header_numeric[column_dollar]])

In [202]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [203]:
header_numeric=np.concatenate((header_numeric,header_additional))

In [204]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [206]:
header_numeric[column_dollar]=np.array([column_name+"_USD" for column_name in header_numeric[column_dollar]])

In [207]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [208]:
column_index_order=[0,1,7,2,8,3,4,9,5,10,6]

In [209]:
header_numeric[column_index_order]

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [210]:
header_numeric=header_numeric[column_index_order]

In [211]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [212]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]],
      shape=(10000, 11))

In [213]:
loan_data_numeric=loan_data_numeric[:,column_index_order]

In [214]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]],
      shape=(10000, 11))

# Interest rate

In [215]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [217]:
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99], shape=(10000,))

In [218]:
loan_data_numeric[:,5]=loan_data_numeric[:,5]/100

In [219]:
loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29], shape=(10000,))

# checkpoint2:numeric

In [220]:
checkpoint_numeric=checkpoint("checkpoint-numeric",header_numeric,loan_data_numeric)

In [221]:
checkpoint_numeric["header"]

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [222]:
checkpoint_numeric["data"]

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]],
      shape=(10000, 11))

# completing the dataset

In [223]:
checkpoint_strings['data'].shape

(10000, 6)

In [224]:
checkpoint_numeric['data'].shape

(10000, 11)

In [226]:
loan_data=np.hstack((checkpoint_numeric['data'],checkpoint_strings['data']))

In [227]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]],
      shape=(10000, 17))

In [228]:
np.isnan(loan_data).sum()

np.int64(0)

In [231]:
header_full=np.concatenate((checkpoint_numeric['header'],checkpoint_strings['header']))

# sorting the dataset

In [232]:
loan_data=loan_data[np.argsort(loan_data[:,0])]

In [233]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]],
      shape=(10000, 17))

# storing new dataset

In [235]:
loan_data=np.vstack((header_full,loan_data))

In [236]:
loan_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'addr_state'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']],
      shape=(10001, 17), dtype='<U32')

In [237]:
np.savetxt("loan-data-preprocessed.csv",loan_data,fmt="%s",delimiter=',')